# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  semearanuncioswebapi:
    image: semearanuncioswebapi
    build:
      context: .
      dockerfile: Anuncios.WebApi/Semear.Anuncios.WebApi/Dockerfile
    ports:
      - "8081:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: semearanuncioswebapi
    depends_on:
      - database

  semearautenticacaowebapi:
    image: semearautenticacaowebapi
    build:
      context: .
      dockerfile: Autenticacao.WebApi/Semear.Autenticacao.WebApi/Dockerfile
    ports:
      - "8082:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: semearautenticacaowebapi
    depends_on:
      - database

  semearsuarioswebapi:
    image: semearsuarioswebapi
    build:
      context: .
      dockerfile: Usuarios.WebApi/Semear.Usuarios.WebApi/Dockerfile
    ports:
      - "8083:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: semearsuarioswebapi
    depends_on:
      - database

  database:
    build: ./data
    environment:
      SA_PASSWORD: "Testando@123"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
        - "1433:1433"
    container_name: database
    hostname: database

volumes:
  mssqldata:

networks:
  semear:
    name: semear-network
