# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  semearanuncioswebapi:
    image: semearanuncioswebapi
    build:
      context: .
      dockerfile: Semear.Anuncios.WebApi/Dockerfile
    ports:
      - 5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
